# Generated by Django 3.2.5 on 2022-01-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('supervisor_name', models.CharField(blank=True, max_length=200)),
                ('project_catg', models.CharField(blank=True, max_length=200)),
                ('others', models.CharField(blank=True, max_length=200)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_description', models.TextField()),
                ('program_lang', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('project_mode', models.CharField(blank=True, max_length=200)),
                ('no_of_member', models.IntegerField()),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
