# Generated by Django 3.2.5 on 2022-01-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
