# Generated by Django 3.2.5 on 2022-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plep_app', '0002_client_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='no_of_member',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
